Upgrade the required version of requests.
With the prior version, you'd get this error:
  ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

Upgrading it to a recent version seems to fix the problem.